from django.urls import path
from .views import (
    create_post, create_post_org, delete_activity, edit_activity, events_orgs, hackathons_org, handle_join_request, join_project_room, learn_search_org, learn_upload_orgs, logout, main_home, my_activity, my_activity_org, notifications, profile_view,  register_user, register_organizer, search_job, events, hackathons,
    project_collab, create_project_room, learn_upload, learn_search,
    organize_event, organize_hackathon, post_job, search_job_orgs, send_join_request, user_home, organizer_home, view_join_requests, view_posts, view_posts_org,
)

urlpatterns = [
    path('register_user/', register_user, name='register_user'),
    path('register_organizer/', register_organizer, name='register_organizer'),
    path('', main_home, name='main_home'),
    path('user_home/', user_home, name='user_home'),  
    path('organizer_home/', organizer_home, name='organizer_home'),  
    path('search_job/', search_job, name='search_job'),
    path('search_job_orgs/', search_job_orgs, name='search_job_orgs'),
    path('events/', events, name='events'),
    path('events_orgs/', events_orgs, name="events_orgs"),
    path('hackathons/', hackathons, name='hackathons'),
    path('hackathons_org/', hackathons_org, name='hackathons_org'),
    path('project_collab/', project_collab, name='project_collab'),
    path('create_project_room/', create_project_room, name='create_project_room'),
    path('learn_upload/', learn_upload, name='learn_upload'),
    path('learn_upload_orgs/', learn_upload_orgs, name='learn_upload_orgs'),
    path('learn_search/', learn_search, name='learn_search'),
    path('learn_search_org/',learn_search_org, name='learn_search_org'),
    path('organize_event/', organize_event, name='organize_event'),
    path('organize_hackathon/', organize_hackathon, name='organize_hackathon'),
    path('post_job/', post_job, name='post_job'),
    path('create_post/', create_post, name='create_post'),
    path('create_post_org',create_post_org, name='create_post_org'),
    path('view_posts/', view_posts, name='view_posts'),
    path('view_posts_org/', view_posts_org, name='view_posts_org'),
    path('logout/', logout, name='logout'),
    path('profile/<str:username>/', profile_view, name='profile_view'),
    path('my_activity/', my_activity, name='my_activity'),
    path('my_activity_org/', my_activity_org, name='my_activity_org'),
    path('edit_activity/<str:activity_type>/<int:activity_id>/', edit_activity, name='edit_activity'),
    path('delete_activity/<str:activity_type>/<int:activity_id>/', delete_activity, name='delete_activity'),
    path('join_project_room/<int:room_id>/', join_project_room, name='join_project_room'),
    path('view_join_requests/', view_join_requests, name='view_join_requests'),
    path('handle_join_request/<int:request_id>/<str:action>/', handle_join_request, name='handle_join_request'),
    path('send_join_request/', send_join_request, name='send_join_request'),
    path('notifications/', notifications, name='notifications'),
    # path('login/normal/', normal_login, name='normal_login'),
    # path('login/organizer/', organizer_login, name='organizer_login'),
]
