# Generated by Django 5.0.3 on 2024-07-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_joinrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('user', 'room')},
        ),
    ]
